version: '3'
services:
  frontend:
    build: ./frontend
    container_name: movie-list-aggregator-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080

  backend:
    build: ./backend
    environment:
      - TMDB_URL
      - TMDB_API_KEY
      - APP_KEY
    container_name: movie-list-aggregator-backend
    volumes:
      - ./backend:/api
    ports:
      - 8000:8000